name: Build and Publish All Containers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Build containers
        run: |
          for recipe in recipes/*.recipe; do
            name=$(basename "$recipe" .recipe | cut -d'-' -f1)
            version=$(basename "$recipe" .recipe | cut -d'-' -f2)
            podman build -f "$recipe" -t "$name:$version"
          done

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push containers
        run: |
          for recipe in recipes/*.recipe; do
            name=$(basename "$recipe" .recipe | cut -d'-' -f1)
            version=$(basename "$recipe" .recipe | cut -d'-' -f2)
            podman tag "$name:$version" "ghcr.io/globus-gladier/aps_recipes/$name:$version"
            podman push "ghcr.io/globus-gladier/aps_recipes/$name:$version"
          done
