name: Build and Publish SSX Container

on:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Build and push SSX container
        run: |
          podman build -f ssx_25.recipe -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ssx:latest
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ssx:latest
