name: Build DIALS Container

on:
  push:
    paths:
      - 'recipes/dials-1.0.0.recipe'
      - '.github/workflows/build-dials.yml'
  pull_request:
    paths:
      - 'recipes/dials-1.0.0.recipe'
      - '.github/workflows/build-dials.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Build container
        run: |
          podman build -f recipes/dials-1.0.0.recipe -t dials:1.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container
        run: |
          podman tag dials:1.0.0 ghcr.io/globus-gladier/aps_recipes/dials:1.0.0
          podman push ghcr.io/globus-gladier/aps_recipes/dials:1.0.0 