name: Validate Recipe Files

on:
  push:
    paths:
      - 'recipes/**'
      - '.pre-commit-config.yaml'
      - '.pre-commit-hooks/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'recipes/**'
      - '.pre-commit-config.yaml'
      - '.pre-commit-hooks/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Install container-structure-test
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

      - name: Build and test all containers
        run: |
          # Find all recipe files
          for recipe in recipes/*.recipe; do
            # Get container name and version from recipe path
            name=$(basename "$recipe" .recipe | cut -d'-' -f1)
            version=$(basename "$recipe" .recipe | cut -d'-' -f2)

            # Build container
            echo "Building $name:$version..."
            podman build -f "$recipe" -t "$name:$version"

            # Run tests if they exist
            test_file="tests/$name-$version.yaml"
            if [ -f "$test_file" ]; then
              echo "Testing $name:$version..."
              container-structure-test test \
                --image "$name:$version" \
                --config "$test_file"
            fi
          done
